#!/bin/bash
#PBS -A csc238
#PBS -N h_matrix_test
#PBS -j oe
#PBS -l walltime=00:10:00,nodes=1

module swap PrgEnv-pgi PrgEnv-gnu
module load cudatoolkit 
module load gsl
export MPICH_RDMA_ENABLED_CUDA=1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/gcc/4.9.3/snos/lib64:/lib:/lustre/atlas/proj-shared/csc238/MPLA/src:/lustre/atlas/proj-shared/csc238/hmglib/src:${GSL_DIR}/lib

cd /lustre/atlas/proj-shared/csc238/MPLA/src

time aprun -n 1 -N 1 ./h_matrix_test 524288 2 1.0e-14 0 100 16 2048 -5 10


